spring:
  application:
    name: Warehouse
  datasource:
#    username: postgres
#    url: jdbc:postgresql://localhost:5432/warehouse
#    password: 1234
      username: neondb_owner
      password: npg_8ZmLW5yApKEt
      url: jdbc:postgresql://ep-fancy-dust-ai0hos94-pooler.c-4.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  mail:
    host: smtp.gmail.com
    port: 587
    username: shuhratbekqodirov1@gmail.com
    password: ouevytrtexmdrjhi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
    test-connection: false

freemarker:
  template-loader-path: classpath:/templates/
  suffix: .ftl


  # Telegram bot konfiguratsiyasi
telegram:
    bot:
      token: 8746719605:AAFIriQFmA8vZ4e2LCBnE7zhl4_GeD2Aix8
      username: WarehouseGold_bot
